//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace infosecrd.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArticle
    {
        public int Id { get; set; }
        public string Titulo { get; set; }
        public string Autor { get; set; }
        public string Body { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public string ImgPath { get; set; }
    }
}
